CLINICAL_DISCLAIMER = """
This system is a research and decision-support tool intended for educational
and investigational purposes only.

It is NOT a medical device and must NOT be used as a sole basis for diagnosis,
treatment, or clinical decision-making.

The predictions generated by this system are based on patterns learned from
historical ECG data and may not generalize to all patient populations,
recording devices, or clinical settings.

A qualified medical professional must always interpret ECG findings in
conjunction with clinical history, physical examination, and additional
diagnostic tests.

The developers assume no responsibility for clinical outcomes resulting
from the use of this system.
"""